// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ClientNotification> subscribeClientNotifications() =>
    RustLib.instance.api
        .crateApiClientNotificationsSubscribeClientNotifications();

Future<void> notifyClient({required ClientNotification notification}) =>
    RustLib.instance.api
        .crateApiClientNotificationsNotifyClient(notification: notification);

class ClientNotification {
  final String title;
  final String message;

  const ClientNotification({
    required this.title,
    required this.message,
  });

  @override
  int get hashCode => title.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClientNotification &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          message == other.message;
}
