// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<StartupCommand> parseStartupCommand({required List<String> args}) =>
    RustLib.instance.api.crateApiStartupCommandsParseStartupCommand(args: args);

Future<void> reportStartupCommandResult(
        {required String scriptName, String? error}) =>
    RustLib.instance.api.crateApiStartupCommandsReportStartupCommandResult(
        scriptName: scriptName, error: error);

class StartupCommand {
  final String? launchFilePath;
  final String? loadJsPath;

  const StartupCommand({
    this.launchFilePath,
    this.loadJsPath,
  });

  @override
  int get hashCode => launchFilePath.hashCode ^ loadJsPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StartupCommand &&
          runtimeType == other.runtimeType &&
          launchFilePath == other.launchFilePath &&
          loadJsPath == other.loadJsPath;
}
